# Dependabot will run on day 22 of each month at 02:44 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "44 2 22 * *"
    open-pull-requests-limit: 20
    assignees:
      - "Jey-Cee"
    versioning-strategy: "increase"
